### ISSUE TITLE
build fails in 0.25.0 with react-dom

### ISSUE THREAD

**Issue by pixelass** [css-modules/css-modulesify#102]
* 💖 `0.24.0`  
* 💖 `0.25.0`  

```js
import {nav} from './style.css'
import React, { Component, propTypes } from 'react'
//import ReactDOM from 'react-dom'
import { Router, Route } from 'react-enroute'
```

* 💖 `0.24.0`  
* 💩 `0.25.0`

```js
import {nav} from './style.css'
import React, { Component, propTypes } from 'react'
import ReactDOM from 'react-dom'
import { Router, Route } from 'react-enroute'
```

```js
import ReactDOM from 'react-dom'
```

Using any command similar to this one I found in a demo

```
babelify -v -t [babelify --presets es2015 --presets react] -p [css-modulesify --after postcss-color-rebeccapurple --after autoprefixer --autoprefixer.browsers '> 5%' -o dist/main.css] -o dist/index.js src/index.js
```

The same issue occurs if I put the transforms in the package.json

```js
{"browserify": {
    "transform": [
      "babelify",
      ["babelify", {
        "presets": ["es2015", "react", "stage-0"]
      }]
    ]
  }
}
```

> Bug: (I  think) the javascript is not fully generated (Browser console: Unexpected Input) and the css file is not generated

**Comment by joshwnj** [comment]
@pixelass thanks for reporting, from what I can see it looks like there was an issue with the stream not ending properly.

Could you please try upgrading to v0.25.1 and let me know if that fixes it?

**Comment by pixelass** [comment]
Seems to work fine.  Thx
