### ISSUE TITLE
Let users choose file extension

### ISSUE THREAD

**Issue by tai2** [css-modules/css-modulesify#110]
I would like to use `.pcss` instead of `.css` as the PostCSS organization [officially suggests](https://twitter.com/PostCSS/status/661645290622083073).

What do you think about adding an option to specify file extension?

**Comment by joshwnj** [comment]
@tai2 sure, I'd be ok with this - and it wouldn't be too hard to introduce that option.

Would you like to try creating a PR for it? I'd be happy to help if you get stuck at any point.

**Comment by tai2** [comment]
I'll try it. Pleas wait a moment.

**Comment by joshwnj** [comment]
Thanks @tai2 , this is published to npm as v0.27.0
