### ISSUE TITLE
Make the PostCSS transforms configurable.

### ISSUE THREAD

**Issue by geelen** [css-modules/css-modulesify#12]
The `FileSystemLoader` passes through the list of plugins to the loader core, but that's not configurable here. I have absolutely no idea how browserify plugins work, but if that set of plugins is configurable then this becomes basically a 'postcssify' that supports `:local` (like https://github.com/geelen/jspm-loader-css or webpack's loader without module-mode), which would be pretty neat.

**Comment by joshgillies** [comment]
Support for this has just been released! Closing.
