### ISSUE TITLE
feature request: add possibility to compile css-modules on the fly

### ISSUE THREAD

**Issue by sullenor** [css-modules/css-modulesify#20]
Hello there!

I thought it would be nice to have a require hook like in [babel](http://babeljs.io/docs/usage/require/). So it will allow you to use css-modules in the universal apps (execute code both on the client and the server).

**Comment by joshwnj** [comment]
It sure would. Take a look at what @joeybaker has been putting together for a similar need over at https://github.com/css-modules/css-modules/issues/13

**Comment by sullenor** [comment]
Thank you for the answer, i'll take a look on it.
