### ISSUE TITLE
File name conflicts

### ISSUE THREAD

**Issue by thejameskyle** [css-modules/css-modulesify#22]
Since css-modulesify only looks at the current file name it can easily run into conflicts with nested directories

**Input**

```css
/* /component-a/component.css */
.input {
  /* ... */
}
```

```css
/* /component-b/component.css */
.input {
  /* ... */
}
```

**Output**

```css
._component__input {
  /* ... */
}

._component__input {
  /* ... */
}
```

**Comment by joshwnj** [comment]
Hi @thejameskyle, you're right that this is the default behaviour, but we recently added support to append a hash to the classnames: https://github.com/css-modules/css-modulesify/blob/master/index.js#L9-L19

And you can see it in action here when you inspect the dom: http://css-modules.github.io/browserify-demo/

**Comment by thejameskyle** [comment]
You might want to enable that by default, otherwise the main benefit of this tool is a false promise.

**Comment by joshwnj** [comment]
Yeah I like the idea of enabling by default too. Definitely on the map for near future.
