### ISSUE TITLE
Should pass options to core modules without needing re-inclusion

### ISSUE THREAD

**Issue by ryngonzalez** [css-modules/css-modulesify#43]
Unless I use the `use` option to re-include the core modules, I can't pass custom options to them, like a custom class name generator. 

```js
  .plugin('css-modulesify', {
    rootDir: __dirname,
    output: `compiled.css`,
    use: [
      "postcss-modules-extract-imports",
      "postcss-modules-local-by-default",
      "postcss-modules-scope",
    ],
    'postcss-modules-scope': {
      generateScopedName: createClassName
    }
```

Anyway we can pass in option without needing to do these re-inclusions?

**Comment by joshwnj** [comment]
@ryngonzalez please take a look at #46 and let me know if that is a better solution for you. Are there any other options on the other plugins you'd like to be able to set?

**Comment by ryngonzalez** [comment]
@joshwnj Looking over the core modules and their potential options, I see [`rewriteUrl`](https://github.com/css-modules/postcss-modules-local-by-default/blob/master/index.js#L158-L162); while I don't want to necessarily pass in my own option for this, I think `css-modulesify` should be passing in something to address #42 to do better `composes` resolution that respects `browserify._options.paths` to search within the correct folder.

Other than that, no other options that should be accessible for the core modules that I can find :+1:

**Comment by ryngonzalez** [comment]
Nice, closing with the merge of #46
