### ISSUE TITLE
class names not scoped using the "use" api

### ISSUE THREAD

**Issue by themitchy** [css-modules/css-modulesify#50]
If any plugins are specified via the `use` option, class names will not be scoped. Worse yet it's not plugin specific because an empty array still results in no scoping of classnames.

css:
```
.widget {
  display: flex;
}
```

plugin configuration:
```
b.plugin(cssModulesify, {
   rootDir: '../',
   output: './dist/foo.css',
   use: [ autoprefixer ]
});
```

With the above the generated css is:

```
.widget {
  display: -webkit-inline-box;
  display: -webkit-inline-flex;
  display: -ms-inline-flexbox;
  display: inline-flex;
}
```

With `use: [ ]` the class name is still not scoped. With `use` completely removed the class will be scoped correctly.

Seems like css-modules + plugins is too common a use case to not support it.

**Comment by themitchy** [comment]
Nope, I'm dumb. Should be using `postcssAfter` instead of `use`.

**Comment by joshwnj** [comment]
You're right @themitchy , this is a bit confusing because it doesn't make so much sense if `use` drops the very plugins that make css modules work.  We hope to address this point (and some others) when we go to v1.0 (discussion in #29)
