### ISSUE TITLE
Can not use url for load a background image in css?

### ISSUE THREAD

**Issue by chenmnkken** [css-modules/css-modulesify#52]
When i use url load a background image.
```
.bg{ background: url(./bar_bg.png) no-repeat 0 1px; }
```

Then compiler error is:
```
Cannot read property 'rewriteUrl' of undefined while parsing file: /xxx/xxx.css
```

How can i resolve this error?

**Comment by tinchoz49** [comment]
This is an error that i found in the postcss-modules-local-by-default [33](https://github.com/css-modules/css-modulesify/issues/33) and was fixed but is seems the module in css-modulesify is not updated.

**Comment by joshwnj** [comment]
Thanks, `css-modulesify` has been upgraded to use the latest dependency - please upgrade to v0.13.0

**Comment by tinchoz49** [comment]
thanks @joshwnj !
