### ISSUE TITLE
Postcss version error

### ISSUE THREAD

**Issue by chenmnkken** [css-modules/css-modulesify#53]
My node is 4.2.1 version, npm is 3.3.9. I installed `css-modulesify`, when i run `css-modulesify` in `browserify`, then error is:

> "Your current PostCSS version is 5.0.10, but postcss-modules-local-by-default uses 4.1.16. Perhaps this is the source of the error below."

I think this is because global `postcss` and `css-modulesify` depend version different, may be this error only in npm 3.x.

**Comment by t128** [comment]
try updating to the latest *css-modulesify* version.

**Comment by joshwnj** [comment]
@chenmnkken can you please confirm whether this still occurs with the latest version? It should be fixed now that we're on postcss v5

**Comment by chenmnkken** [comment]
@joshwnj Update the css-modulesify to 0.13.0, it's no problem, thanks.
