### ISSUE TITLE
Works with postcss-modules-values?

### ISSUE THREAD

**Issue by bcomnes** [css-modules/css-modulesify#54]
Is there a way to get css-modulesify to work with https://github.com/css-modules/postcss-modules-values ?

**Comment by bcomnes** [comment]
Looks like there is a branch for it!  My bad.

**Comment by IanVS** [comment]
@bcomnes, did you get this working?  I'm having difficulty using postcss-modules-values, but I'm likely configuring it incorrectly.  Any tips?
