### ISSUE TITLE
composes duplicates dependancies

### ISSUE THREAD

**Issue by themitchy** [css-modules/css-modulesify#58]
If multiple stylesheets are imported (or components importing different stylesheets) and those files compose from a common stylesheet (ie. `icons.css`) then the styles and composes of the common stylesheet will be duplicated for every import.

This [gist](https://gist.github.com/themitchy/b6dcb7fd8c249ab97433) shows a simple jsx which imports 2 modules, each of which imports a stylesheet composing from `icons.css`. Since `icons.css` composes from font-awesome, all of font-awesome is included in the resulting css twice.

**Comment by loklaan** [comment]
Could you try out #57, which should resolve this issue.

**Comment by themitchy** [comment]
No dice on #57 - still results in dupes of everything in the common stylesheet.

**Comment by joshwnj** [comment]
@themitchy please take a look at #61 to see whether that fixes the issue.

**Comment by themitchy** [comment]
That did it! Thanks @joshwnj !
