### ISSUE TITLE
Destination CSS file is not updating using watchify

### ISSUE THREAD

**Issue by tinchoz49** [css-modules/css-modulesify#63]
Hi guys, working with your example: https://github.com/css-modules/browserify-demo
I ran into this problem: using watchify, the event emit 'update' works great but is not updating the dest css file.

run: ```npm start``` and edit a css file from the src folder. 
The log gets ``` info browserify: /index.js 682ms (bundle)``` but the dest css file is not changed.

**Comment by tinchoz49** [comment]
I found that if you comment the line 47 and 48 of the [file-system-loader](https://github.com/css-modules/css-modules-loader-core/blob/master/src/file-system-loader.js) works.
What is the objetive of create a token based on the filename? If is for caching css files I think is better create a checksum based on the content file.

**Comment by joshwnj** [comment]
Thanks for reporting this @tinchoz49 . It looks like a solution shouldn't be too tricky but there are a few different factors at play so we'll need to make sure other functionality isn't affected. Would you be interested in helping to put together a failing test case for this bug?

**Comment by justgook** [comment]
By commenting those lines it updates map, but not rebuild css-file

**Comment by markuplab** [comment]
Do you need help with this problem? I can try make fixes.

**Comment by justgook** [comment]
for me it is main stopper to use css-modules in my projects..

**Comment by joshwnj** [comment]
Thanks for the offer @markuplab - that'd be great, especially if you're able to help with writing a test case for this issue.

**Comment by joshwnj** [comment]
Status on this: I'm looking into a better way of walking the dependency tree, which I'm hoping will be the key to getting watchify working properly. But my time is limited so if anyone else cares to help that would be greatly appreciated :)

**Comment by joshwnj** [comment]
From early trials the solution appears to be working :ok_woman: Need to check a few more edges and then will put together a release.

**Comment by markuplab** [comment]
Ohhh it's amazing :) Can you create PR?

**Comment by markuplab** [comment]
@joshwnj Hi, can you say, when release with this fix will be ready? We want start project with css-modules, but watchify problem block it, if you have troubles with time, we can fork module and fix it problem, or we can wait when you fix it?

**Comment by joshwnj** [comment]
@markuplab I've pushed #64, which still has a couple of bugs and failing tests (and I believe will need https://github.com/css-modules/css-modules-loader-core/pull/62 to be merged in order to pass as well).

But even at this point it partly works :) And hopefully it gives you an idea of where it's heading, so please take a look and feel free to fix any bugs you see.  I'm out of time today but hopefully will have time to wrap it up tomorrow.

**Comment by snikch** [comment]
@joshwnj I've been watching this issue, and have tried out #64 and this seems to fix the issue for me.

**Comment by snikch** [comment]
Hrm, I spoke too soon. It will handle a change which it hasn't seen before, but making a change then reverting it will not result in an update.

For example, running with a `padding: 10px`, then changing to `padding: 60px` will correctly rebuild the css, but changing back to `padding: 10px` will not. Updating to a new value, such as `padding: 600px`, will trigger an update.

**Comment by tinchoz49** [comment]
works great to me! :+1: 

now my problem is the issue #65 :(
