### ISSUE TITLE
PostCSS Plugins not work

### ISSUE THREAD

**Issue by justgook** [css-modules/css-modulesify#65]
i have add `postbuild` script to mimify/autoprefix my css  
based on [README](https://github.com/css-modules/css-modulesify#postcss-plugins) there is possibility add those plugins in "--after" argument - but looks like it don't work
or maybe im doing something wrong?
```
...
    "prebuild": "mkdir -p public && cp src/index.html public && browserify -r morearty -r react -r react-dom > public/vendor.js",
    "build": "NODE_ENV=production browserify -p [css-modulesify  --after cssnano -o public/main.css] src/index.coffee --exclude morearty --exclude react --exclude react-dom --extension=.cjsx --extension=.coffee -o public/index.js -v",
    "postbuild": "cssnano ./public/main.css ./public/main.min.css ",
...
```

https://github.com/justgook/sokoban-react

**Comment by tinchoz49** [comment]
same problem here! in version 0.13.0 works. Tested with my async postcss plugin ```postcss-copy```.

I think that this commit f9a2ea2825f219b05ddd931c6a1bd3cffdad2709 broke the loader of postcss plugin.

**Comment by justgook** [comment]
revert / reimplement ?

**Comment by joshwnj** [comment]
Oh, you're right about that commit breaking it sorry - looks like we're now creating the `loader` _before_ the plugins list has been fully populated.

Will submit a patch today, is anyone able to help with writing a test case along the lines of _"extra postcss plugins are applied"_?

**Comment by joshwnj** [comment]
@tinchoz49 / @justgook can you please check #67 to see whether this fixes the issue in your case?

**Comment by tinchoz49** [comment]
hi @joshwnj ! with your change the postcss plugins like autoprefixer works great :+1: , but it seems that the async plugins not.

I made an example of one async plugin and the process of css-modulesify never finish.

```javascript
function asyncPlugin() {
    return postcss.plugin('async-plugin', function (opts) {
        return function (css, result) {
            return new Promise(function (resolve, reject) {
                setTimeout(function () {
                    resolve();
                }, 2000);
            });
        };
    });
}

var bundler = browserify({
        entries: [sourceFile]
    })
    .plugin(watchify)
    .plugin(cssModulesify, {
        rootDir: __dirname,
        output: path.join(destFolder, cssDestFile),
        postcssAfter: [
            autoprefixer,
            asyncPlugin
        ]
    });
```

**Comment by tinchoz49** [comment]
if you want i can upload tomorrow my example repository where i'm testing this things ;)

**Comment by joshwnj** [comment]
Thanks @tinchoz49 - an example repo would be great.  I think if #67 solves part of the issue I'll go ahead and merge it tomorrow, and we can create a new issue for async plugins.

`postcss-copy` looks cool btw! I'll try it out in my next project.

**Comment by justgook** [comment]
+1

**Comment by joshwnj** [comment]
@tinchoz49 I've created #68 to track a solution to the issue you mentioned with async plugins
