### ISSUE TITLE
Async PostCSS Plugins

### ISSUE THREAD

**Issue by joshwnj** [css-modules/css-modulesify#68]
There is an issue with async PostCSS plugins as described here: https://github.com/css-modules/css-modulesify/issues/65#issuecomment-161503995

**Comment by tinchoz49** [comment]
@joshwnj the repository that i told you is ready ;) sorry for the delay.

https://github.com/geut/eg-assets-css-modulesify/tree/fix-async-plugins

**Comment by joshwnj** [comment]
@tinchoz49 thanks!

**Comment by tinchoz49** [comment]
hi @joshwnj ! i was testing again the example and i found that the error with postcss-copy was my fault :( (a undefined variable in the example that i didn't see). I really sorry for bothering you. 

i'm going to close this issue. Everything is working ok!

Thanks!

**Comment by joshwnj** [comment]
no worries - glad to hear it :)
