### ISSUE TITLE
`require('…')` call in output contains full filepath

### ISSUE THREAD

**Issue by snikch** [css-modules/css-modulesify#69]
I've probably configured something wrong here, but I appear to be getting the full filepath in my browserified output. This appears to be limited only to the dependant files, i.e. files that are in `composes` calls. The normal javascript files have the correct, relative, filepaths.

```js
28:[function(require,module,exports){
require('/Users/mal/Code/src/github.com/…/…/frontend/oauth/src/styles/components/button.css')
module.exports = {"header":"_components_login__header", …}
},
{"/Users/mal/Code/src/github.com/…/…/frontend/oauth/src/styles/components/button.css":26}]
```

Any ideas on what I'm doing wrong here?

**Comment by joeybaker** [comment]
Without seeing your config, it's a bit hard to say, but have you had a look at the [`rootDir` option](https://github.com/css-modules/css-modulesify#options)?

**Comment by snikch** [comment]
Here's my config. I've also tried with the `__dirname` option to no avail. Note that the class names are correctly relative to the root dir.

```js
  {
    rootDir: 'src/styles/',
    output: 'dist/css/oauth.css',
    postcssAfter: [autoprefixer]
  }
```

**Comment by joeybaker** [comment]
> I've also tried with the `__dirname` option to no avail. 

Does that mean you tried something like:

```js
{
   rootDir: path.join(__dirname, 'src', 'styles')
}
```

If not, maybe give that a shot?

If so, what's your setup look like?

**Comment by joshwnj** [comment]
I believe this is resolved by using absolute paths, we can reopen if it turns out to be something else.
