### ISSUE TITLE
Add doc for the `global` option

### ISSUE THREAD

**Issue by inoc603** [css-modules/css-modulesify#71]
I was trying to use a sub module which imports css, and I kept getting `ParseError: Unexpected token` at the first character of the css file when bundling.

After digging through the tests I found 2 test cases named `import-node-module` and `compose-node-module`, which shows that when dealing with node modules, the `global` option should be set to true.

But the `global` option is not documented in README, and I'm not really sure what it does. Can someone update the doc with the usage of this option?

**Comment by kylelamse** [comment]
I agree.  I am trying to figure out anything about it but there is literally no documentation for it.

**Comment by joshwnj** [comment]
Added in https://github.com/css-modules/css-modulesify/pull/93/files
