### ISSUE TITLE
postcss-modules-values is now included in default plugins

### ISSUE THREAD

**Issue by IanVS** [css-modules/css-modulesify#72]
The [readme](https://github.com/css-modules/css-modulesify#postcss-plugins) does not mention that [postcss-modules-values](https://github.com/css-modules/postcss-modules-values) is now included in the default set of plugins (from [css-modules-loader-core](https://github.com/css-modules/css-modules-loader-core)).

Running with `--after postcss-modules-values` was giving an error, and it took me a while to figure out why.  Updating the readme may avoid such headaches for others.

**Comment by joshwnj** [comment]
thanks for bringing this up @IanVS . Would you be interested in making a PR to update the readme?

**Comment by IanVS** [comment]
Sure thing, will do it tonight.
