### ISSUE TITLE
consider Browserify basedir for rootDir

### ISSUE THREAD

**Issue by tjallingt** [css-modules/css-modulesify#75]
An example of a relatively common way to call browserify is this:
```
browserify({ 
	entries: "entry.js",
	basedir: './src',
})
```
Why would you have to specify the `rootDir` when it is probably the same as browserify's `basedir`?
I would suggest to have `css-modulesify` use the `rootDir` when specified, then try the `browserify._options.basedir` and only if that is also not specified use the current folder.

**Comment by joshwnj** [comment]
Good idea. Would you like to make the PR otherwise I'm happy to.
