### ISSUE TITLE
Exporting static CSS

### ISSUE THREAD

**Issue by rtsao** [css-modules/css-modulesify#8]
Right now, the only supported way to output the modular styles at build time is to make a file like this:

```javascript
console.log([		
  require('./styles1.css'),		
  require('./styles2.css')		
].join('\n'));
```

then run the transform on it:
```bash
browserify -t css-modulesify example/export-css.js | node > output.css
```

This is fairly inconvenient. I'd be much nicer if there was a way to output the final css without this additional boilerplate. This either has to be added and maintained manually or generated somehow, which necessitates even more tooling.

I was thinking of two ways on how this might be improved:

1) Turn the browserify transform into a browserify plugin
This will allow for creating additional outputs (e.g. https://github.com/substack/factor-bundle), so it would be possible to additionally output the static css at build time (perhaps depending on a plugin argument with the filename).

2) Remove the postcss dependency from the transform and assume the css is already in CSSI format. Then consumers can simply use the postcss plugins directly to get the static css files. Now the scope of the browserify transform smaller, merely serving as loader for CSSI.

Thoughts?

**Comment by joeybaker** [comment]
@rtsao agreed. This is one of the largest issues with css-modulesify right now IMO. I'd vote for option 1.

**Comment by joshwnj** [comment]
@rtsao @joeybaker yes Option 1 is what we're heading towards (browserify plugin that produces a css bundle alongside the js bundle).  PRs welcome :)

**Comment by joshgillies** [comment]
Absolutely. A Browserify [plugin](https://github.com/substack/node-browserify/blob/master/readme.markdown#bpluginplugin-opts) is the appropriate course of action here. :thumbsup:

**Comment by rtsao** [comment]
Cool, I can probably help with this. I just wanted to make sure everyone is on the same page.

**Comment by joshwnj** [comment]
@rtsao :+1:
