### ISSUE TITLE
Extensions option is not recognized

### ISSUE THREAD

**Issue by MrCheater** [css-modules/css-modulesify#86]
setting extensions to ['.scss'] gives error:

Unexpected token

**Comment by MrCheater** [comment]
https://github.com/css-modules/css-modules-require-hook#extensions-array

**Comment by joshwnj** [comment]
@MrCheater we haven't implemented an `extensions` option yet, did you mean to post this issue on the https://github.com/css-modules/css-modules-require-hook repo instead?

**Comment by MrCheater** [comment]
I do not want use *.CSS . I want use *.SCSS. For *.CSS WebStorm syntax highlighting wrong. CSS-hook can use options.extensions. CSS-modulesify can not use options.extensions.
We need the support for Filename.ANY_EXTENSION
